use super::Screen;

pub(super) fn help_lines_for_screen(screen: &Screen) -> Vec<String> {
    match screen {
        Screen::Dashboard { .. } => vec![
            "Dashboard".into(),
            "".into(),
            "Home screen with summary cards, environment status, and quick actions.".into(),
            "".into(),
            "Keys:".into(),
            "  1/2/3/4         Jump to Dashboard/Tools/Configure/Skills".into(),
            "  Left/Right      Cycle top-level pages (tabs stay focused)".into(),
            "  Enter/Down      Enter current page content".into(),
            "  Tab             Focus top page tabs".into(),
            "  Esc             Content -> Tabs, Tabs -> Previous page".into(),
            "  j/k      Scroll status area".into(),
            "  ?        Show this help".into(),
            "  q        Quit ai-setup".into(),
        ],
        Screen::Tools(_) => vec![
            "Manage Tools".into(),
            "".into(),
            "Unified list for install, update, and uninstall.".into(),
            "Actions run on selected + actionable tools only.".into(),
            "".into(),
            "Keys:".into(),
            "  1/2/3/4      Jump to Dashboard/Tools/Configure/Skills".into(),
            "  i / u / x    Run install / update / uninstall on current selection".into(),
            "  Enter        Enter Selection detail".into(),
            "  Esc          Exit Selection detail; on list, go back".into(),
            "  Left/Right   Horizontal focus: list/detail".into(),
            "  Up/Down      Move list or scroll detail".into(),
            "  Tab          Focus top page tabs".into(),
            "  j/k          Same as Up/Down".into(),
            "  Space        Toggle current tool".into(),
            "  a            Select all tools".into(),
            "  m            Select installable (missing)".into(),
            "  p            Select installed".into(),
            "  c            Clear selection".into(),
            "  r            Refresh status".into(),
            "  ?            Show this help".into(),
        ],
        Screen::ConfigMenu { .. } => vec![
            "Configure".into(),
            "".into(),
            "Configure global editor/proxy and per-tool settings.".into(),
            "".into(),
            "Keys:".into(),
            "  1/2/3/4          Jump to Dashboard/Tools/Configure/Skills".into(),
            "  j/k or Up/Down   Move selection".into(),
            "  Tab              Focus top page tabs".into(),
            "  Enter            Open selected form".into(),
            "  Esc              Content -> Tabs, Tabs -> Previous page".into(),
            "  ?                Show this help".into(),
        ],
        Screen::Form(form) => vec![
            format!("{} form", form.title),
            "".into(),
            "Edit fields directly. Secret values stay masked in the UI.".into(),
            "".into(),
            "Keys:".into(),
            "  Type text        Append to current field".into(),
            "  Backspace        Delete from current field".into(),
            "  Tab / j / Down   Next field or action".into(),
            "  Shift+Tab / k / Up   Previous field or action".into(),
            "  Enter on Save    Write configuration".into(),
            "  Enter on Open in editor   Open config file with global editor".into(),
            "  o                Open config file with global editor".into(),
            "  Enter on Back    Return to Configure".into(),
            "  Esc              Cancel and return".into(),
            "  ?                Show this help".into(),
        ],
        Screen::SkillSelection { .. } => vec![
            "Skills".into(),
            "".into(),
            "Install or update detected Claude skills into ~/.claude/skills.".into(),
            "".into(),
            "Keys:".into(),
            "  1/2/3/4          Jump to Dashboard/Tools/Configure/Skills".into(),
            "  j/k or Up/Down   Move selection".into(),
            "  Tab              Focus top page tabs".into(),
            "  Space            Toggle current skill".into(),
            "  a                Select all skills".into(),
            "  c                Clear all skills".into(),
            "  Enter on Install selected   Copy selected skills".into(),
            "  Enter on Back    Return to dashboard".into(),
            "  Esc              Content -> Tabs, Tabs -> Previous page".into(),
            "  ?                Show this help".into(),
        ],
        Screen::Output { .. } => vec![
            "Output".into(),
            "".into(),
            "Shows command output, confirmations, and help.".into(),
            "".into(),
            "Keys:".into(),
            "  j/k or Up/Down   Scroll output".into(),
            "  Tab              Focus top page tabs".into(),
            "  Enter/Esc        Return to previous page (after run completes)".into(),
            "  q                Quit ai-setup".into(),
            "  ?                Replace with help".into(),
        ],
    }
}
